In [2]:
import numpy as np
import pandas as pd
import re
import nltk

In [3]:
data_file = 'shark_tank_data.csv'

load2 = pd.read_csv(data_file)


#Only keeping rows where ASK_Valuation is not null
load2 = load2[load2['ASK_Valuation'].notna()]

load2.head()

,Season,Episode,Business,Description,Deal,Category,Entrepreneur Gender,State,ASK_Equity,ASK_Amount,...,Barbara Corcoran,Mark Cuban,Lori Greiner,Robert Herjavec,Daymond John,Kevin O'Leary,Guest,# Sharks,Investment/shark,Notes
0,1,1,Ava the Elephant,NaN,1,Health/Wellness,Female,NaN,15.00%,50000.0,...,1,0,0,0,0,0,0,1.0,50000.0,NaN
1,1,1,Mr. Tod's Pie Factory,NaN,1,Food and Beverage,Male,NJ,10.00%,460000.0,...,1,0,0,0,1,0,0,2.0,230000.0,NaN
6,1,2,Classroom Jams,NaN,1,Children/Education,Male,NaN,10.00%,250000.0,...,1,1,0,1,1,1,0,5.0,50000.0,5% royalty for the entrepreneur
263,5,1,Sweet Ballz,NaN,1,Food and Beverage,Male,NaN,10.00%,250000.0,...,1,1,0,0,0,0,0,2.0,125000.0,NaN
264,5,1,Postcard on the Run,NaN,1,Software/Tech,Male,NaN,5.00%,300000.0,...,0,0,0,1,0,0,0,1.0,300000.0,NaN

In [4]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(load2,test_size=0.25)

In [55]:
train_corpus = []
test_corpus = []
for each in train['ASK_Valuation']:
    train_corpus.append(each)
for each in test['ASK_Valuation']:
    test_corpus.append(each)
## Start creating them
from sklearn.feature_extraction import DictVectorizer
v = DictVectorizer()
train_features = np.array(train_corpus).reshape(-1,1)
test_features = np.array(test_corpus).reshape(-1,1)

In [28]:
print(train_features)
print(test_features)

[[ 3666667.]
 [16000000.]
 [ 1000000.]
 [  800000.]
 [ 3500000.]
 [  600000.]
 [ 6000000.]
 [ 3000000.]
 [ 8000000.]
 [ 1000000.]
 [ 1000000.]
 [ 4600000.]
 [  300000.]
 [ 1000000.]
 [ 5000000.]
 [ 5000000.]
 [ 4000000.]
 [ 1000000.]
 [ 4285714.]
 [ 5500000.]
 [  625000.]
 [ 1250000.]
 [10000000.]
 [ 1500000.]
 [ 3000000.]
 [10000000.]
 [  400000.]
 [ 2500000.]
 [ 3000000.]
 [ 3000000.]
 [  800000.]
 [ 4000000.]
 [  500000.]
 [ 3500000.]
 [ 1333333.]
 [  750000.]
 [ 4000000.]
 [14285714.]
 [ 2000000.]
 [ 3000000.]
 [12500000.]
 [  250000.]
 [ 8333333.]
 [13333333.]
 [ 2500000.]
 [  625000.]
 [  250000.]
 [ 2500000.]
 [ 4000000.]
 [  750000.]
 [  800000.]
 [ 4000000.]
 [ 2500000.]
 [ 1666667.]
 [ 2500000.]
 [10000000.]
 [ 5000000.]
 [ 2000000.]
 [ 2000000.]
 [  100000.]
 [ 4600000.]
 [ 1666667.]
 [ 5000000.]
 [ 1000000.]
 [ 1250000.]
 [ 1000000.]
 [ 2000000.]
 [ 1000000.]
 [ 4000000.]
 [  625000.]
 [ 2857143.]
 [ 1000000.]
 [ 4000000.]
 [ 4000000.]
 [  750000.]
 [  800000.]
 [ 2500000.]
 [ 1000000.]
 [ 3000000.]
 [ 1500000.]
 [ 1500000.]
 [40000000.]
 [ 7500000.]
 [  375000.]
 [  625000.]
 [ 4250000.]
 [20000000.]
 [  666667.]
 [  400000.]
 [ 2500000.]
 [  750000.]
 [10000000.]
 [ 3000000.]
 [10000000.]
 [ 1000000.]
 [  500000.]
 [  600000.]
 [ 2000000.]
 [ 5000000.]
 [ 2666667.]
 [ 2500000.]
 [ 1000000.]
 [ 1600000.]
 [ 1428571.]
 [  500000.]
 [ 1500000.]
 [ 1500000.]
 [  666667.]
 [  600000.]
 [ 1140000.]
 [  757576.]
 [ 7500000.]
 [ 5000000.]
 [ 2000000.]
 [10000000.]
 [ 2500000.]
 [  600000.]
 [ 1250000.]
 [  625000.]
 [10000000.]
 [ 2000000.]
 [ 1500000.]
 [ 1000000.]
 [ 2000000.]
 [ 4000000.]
 [13000000.]
 [ 5000000.]
 [ 4000000.]
 [20000000.]
 [  500000.]
 [ 5000000.]
 [ 3000000.]
 [  714286.]
 [ 2666667.]
 [ 3000000.]
 [10000000.]
 [  500000.]
 [ 3125000.]
 [ 1500000.]
 [  500000.]
 [  200000.]
 [ 1000000.]
 [30000000.]
 [ 2400000.]
 [ 2500000.]
 [28000000.]
 [  500000.]
 [  850000.]
 [  250000.]
 [11000000.]
 [ 2333333.]
 [16666667.]
 [  266667.]
 [ 1250000.]
 [  750000.]
 [  375000.]
 [ 2500000.]
 [ 1500000.]
 [  600000.]
 [  500000.]
 [ 1500000.]
 [  750000.]
 [  333333.]
 [  600000.]
 [  400000.]
 [  250000.]
 [ 6000000.]
 [ 5000000.]
 [10000000.]
 [ 1000000.]
 [ 5000000.]
 [  500000.]
 [ 2000000.]
 [ 3000000.]
 [ 4000000.]
 [ 4000000.]
 [  300300.]
 [10000000.]
 [  333333.]
 [ 3250000.]
 [ 1000000.]
 [ 1000000.]
 [  625000.]
 [  266667.]
 [  916667.]
 [ 2000000.]
 [ 1500000.]
 [ 1500000.]
 [ 3000000.]
 [ 1000000.]
 [ 7500000.]
 [  375000.]
 [ 5714286.]
 [ 3000000.]
 [  750000.]
 [14000000.]
 [12500000.]
 [ 1000000.]
 [ 2500000.]
 [  500000.]
 [ 5000000.]
 [ 1500000.]
 [11111111.]
 [ 1250000.]
 [  500000.]
 [ 1666667.]
 [  666667.]
 [12500000.]
 [  266667.]
 [ 3000000.]
 [  400000.]
 [  533333.]
 [ 1500000.]
 [  375000.]
 [ 2000000.]
 [ 3000000.]
 [ 1250000.]
 [ 3000000.]
 [ 1538462.]
 [ 1500000.]
 [ 1166667.]
 [ 4000000.]
 [ 1000000.]
 [ 1500000.]
 [ 7142857.]
 [ 1333333.]
 [ 2000000.]
 [ 2500000.]
 [10000000.]
 [ 2000000.]
 [  300000.]
 [ 1600000.]
 [ 1000000.]
 [  500000.]
 [  500000.]
 [  666667.]
 [  800000.]
 [ 7000000.]
 [ 1500000.]
 [ 2500000.]
 [  333333.]
 [ 1500000.]
 [20000000.]
 [ 1000000.]
 [  833333.]
 [ 3000000.]
 [  800000.]
 [ 2500000.]
 [10000000.]
 [ 1250000.]
 [ 2000000.]
 [  500000.]
 [ 1000000.]
 [ 1000000.]
 [  733333.]
 [ 6000000.]
 [  242424.]
 [ 3500000.]
 [  500000.]
 [ 2500000.]
 [  666667.]
 [  250000.]
 [  300000.]
 [  500000.]
 [ 1500000.]
 [ 4000000.]
 [ 1000000.]
 [ 1000000.]
 [ 3000000.]
 [  800000.]
 [ 2500000.]
 [ 4000000.]
 [ 3333333.]
 [ 3750000.]
 [  250000.]
 [12500000.]
 [  500000.]
 [ 2500000.]
 [20000000.]
 [ 1000000.]
 [ 2666667.]
 [  900000.]
 [ 2500000.]
 [ 1875000.]
 [ 2500000.]
 [ 1000000.]
 [  250000.]
 [ 1000000.]
 [  750000.]
 [ 4285714.]
 [10000000.]
 [  600000.]
 [ 3500000.]
 [  428571.]
 [  375000.]
 [  375000.]
 [ 2000000.]
 [  500000.]
 [  666667.]
 [ 3000000.]
 [ 1000000.]
 [ 1500000.]
 [ 1500000.]
 [ 7500000.]
 [10000000.]
 [  533333.]
 [ 1000000.]
 [ 2000000.]
 [ 5000000.]
 [ 7500000.]
 [ 1200000.]
 [ 1000000.]
 [  250000.]
 [25000000.]
 [ 4166667.]
 [16666667.]
 [ 6000000.]
 [20000000.]
 [ 2000000.]
 [ 6000000.]
 [ 1000000.]
 [ 5714286.]
 [10000000.]
 [  400000.]
 [ 1750000.]
 [ 3000000.]
 [10000000.]
 [ 1333333.]
 [ 1333333.]
 [  166667.]
 [ 3000000.]
 [ 3000000.]
 [  800000.]
 [  500000.]
 [ 1000000.]
 [ 4687500.]
 [ 2000000.]
 [ 1470588.]
 [ 1000000.]
 [ 1000000.]
 [ 1000000.]
 [ 1000000.]
 [  750000.]
 [  333333.]
 [ 6000000.]
 [ 1333333.]
 [  500000.]
 [  375000.]
 [ 2500000.]
 [  400000.]
 [ 2000000.]
 [ 2000000.]
 [  333333.]
 [ 3000000.]
 [  300000.]
 [  750000.]
 [ 4000000.]
 [ 8000000.]
 [  500000.]
 [ 1000000.]
 [ 5000000.]
 [ 2600000.]
 [  100000.]
 [  250000.]
 [ 2000000.]
 [ 3000000.]
 [18750000.]
 [ 2500000.]
 [20000000.]
 [15000000.]
 [  500000.]
 [20000000.]
 [ 1800000.]
 [12500000.]
 [ 2500000.]
 [ 2000000.]
 [  458333.]
 [ 2500000.]
 [25000000.]
 [ 3500000.]
 [ 2000000.]
 [ 7142857.]
 [ 1500000.]
 [ 1000000.]
 [ 2000000.]
 [ 1000000.]
 [  500000.]
 [  750000.]
 [ 2000000.]
 [ 1750000.]
 [ 1000000.]
 [ 7000000.]
 [ 2000000.]
 [  950000.]
 [10000000.]
 [18750000.]
 [ 2500000.]
 [  500000.]
 [  250000.]
 [ 3000000.]
 [10000000.]
 [ 1500000.]
 [ 6250000.]
 [ 2000000.]
 [ 1000000.]
 [  300000.]
 [  220000.]
 [ 2500000.]
 [ 1000000.]
 [ 7000000.]
 [ 4500000.]
 [  666667.]
 [ 1333333.]
 [ 2500000.]
 [  120000.]
 [  625000.]
 [ 3000000.]
 [10000000.]
 [10000000.]
 [ 1500000.]
 [  375000.]
 [  750000.]
 [10000000.]
 [ 2250000.]
 [  250000.]
 [ 1666667.]
 [ 1000000.]
 [ 4000000.]
 [ 3333333.]
 [ 1000000.]
 [ 4000000.]
 [ 2000000.]
 [ 8333333.]
 [ 5000000.]
 [  500000.]
 [ 2000000.]
 [ 1000000.]
 [  125000.]
 [ 8333333.]
 [ 8000000.]
 [ 6500000.]
 [ 2000000.]
 [  500000.]
 [ 1500000.]
 [  400000.]
 [ 5000000.]
 [  500000.]
 [  533333.]
 [10000000.]
 [  600000.]
 [ 1250000.]
 [10000000.]
 [ 2500000.]
 [  500000.]
 [ 5000000.]
 [ 5000000.]
 [ 1000000.]
 [14814815.]
 [ 2000000.]
 [ 2500000.]
 [  400000.]
 [ 4000000.]
 [ 7500000.]
 [ 2000000.]
 [ 3000000.]
 [  454545.]
 [ 1333333.]
 [  375000.]
 [ 4000000.]
 [12000000.]
 [ 1000000.]
 [  750000.]
 [  384615.]
 [ 3000000.]
 [ 5000000.]
 [ 2500000.]
 [ 4000000.]
 [ 2500000.]
 [  689655.]
 [ 5000000.]
 [  500000.]
 [ 4000000.]
 [  500000.]
 [  333333.]
 [ 2500000.]
 [  416667.]
 [ 2500000.]
 [ 3000000.]
 [  500000.]
 [  100000.]
 [ 6250000.]
 [ 3000000.]
 [10000000.]
 [  250000.]
 [ 5000000.]
 [ 1000000.]
 [20000000.]
 [ 3333333.]
 [  500000.]
 [ 2500000.]
 [  900000.]
 [ 1000000.]
 [ 7000000.]
 [ 1250000.]
 [ 1000000.]
 [10000000.]
 [ 2500000.]
 [ 5000000.]
 [ 1000000.]
 [ 1000000.]
 [18750000.]
 [ 1000000.]
 [10000000.]
 [  500000.]
 [ 1000000.]
 [ 3000000.]
 [  250000.]
 [  333333.]
 [ 3500000.]
 [13500000.]
 [  500000.]
 [ 1500000.]
 [  500000.]
 [ 1000000.]
 [ 1250000.]
 [ 5000000.]
 [20000000.]
 [ 1000000.]
 [  400000.]
 [  500000.]
 [  625000.]
 [ 3000000.]
 [  250000.]
 [ 5000000.]
 [  600000.]
 [ 1000000.]
 [ 4000000.]
 [10000000.]
 [ 1500000.]
 [ 1250000.]
 [ 1250000.]
 [25000000.]
 [ 4000000.]
 [10000000.]
 [15000000.]
 [  250000.]
 [ 1875000.]]

In [43]:
# Import ML models from sklearn
from sklearn.linear_model import LogisticRegression # Regression classifier
from sklearn.tree import DecisionTreeClassifier # Decision Tree classifier
from sklearn import svm # Support Vector Machine
from sklearn.linear_model import SGDClassifier # Stochastic Gradient Descent Classifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier # Random Forest and Gradient Boosting Classifier
from sklearn.naive_bayes import MultinomialNB # Naive Bayes Classifier 
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix # Some metrics to check the performance of the models

In [56]:
#these are tunable to achieve max accuracy


Classifiers = {#'LR':LogisticRegression(random_state=42,C=5,max_iter=200),
               'DTC':DecisionTreeClassifier(random_state=42,min_samples_leaf=2),
               #'RF':RandomForestClassifier(random_state=42,n_estimators=100,n_jobs=-1),
               'GBC':GradientBoostingClassifier(random_state=42,n_estimators=400,learning_rate=0.35),
               #'SGD':SGDClassifier(loss="hinge", penalty="l2"),
               #'SVM':svm.SVC(kernel='linear', C=0.10),
               #'NB':MultinomialNB(alpha=.05)
}

In [57]:
#Pipeline to reuse the code
def ML_Pipeline(clf_name):
    clf = Classifiers[clf_name]
    fit = clf.fit(train_features,train['Deal'])
    pred = clf.predict(test_features)
    Accuracy = accuracy_score(test['Deal'],pred)
    Confusion_matrix = confusion_matrix(test['Deal'],pred)
    print('==='*20)
    print('Accuracy = '+str(Accuracy))
    print('==='*20) 
    print(Confusion_matrix)

# # ML Code in Individual Blocks

In [47]:
ML_Pipeline('DTC')

============================================================
Accuracy = 0.5519125683060109
============================================================
[[23 38]
 [44 78]]

In [49]:
ML_Pipeline('GBC')

============================================================
Accuracy = 0.5355191256830601
============================================================
[[21 40]
 [45 77]]